#!/bin/bash

# liar update script for .liar_software
#
# To be called in crontab:
#
# 45 7 * * Tue,Fri ~/Sources/liar-update-software/liar-update-software ~/Sources/liar/
LIAR_SOFTWARE_FILE=.liar_software

# Make sure Maven and Java are in the crontab environment
JAVA_HOME=/usr/lib/jvm/jdk8/jdk1.8.0_231
# Cannot make more GraalVM recent versions work with native-image-maven-plugin
GRAAL_VM_HOME=~/Programs/graalvm_rc16/graalvm-ce-1.0.0-rc16
PATH=~/bin:${JAVA_HOME}/bin:$PATH

liar_update_repository=$(dirname "$0")
liar_repository="$1"
exec > "${liar_update_repository}/output.log" 2>&1

# debug
java -version
which java
mvn -version
echo "PATH=${PATH}"
echo "JAVA_HOME=${JAVA_HOME}"

cd "${liar_update_repository}"

# Build native image
if [ ! -f  "./target/SoftwareUpdateRepository.native" ]; then
    make LIAR_REPOSITORY="${liar_repository}" install_native
fi

# Run update
export JAVA_HOME
make LIAR_REPOSITORY="${liar_repository}" update_native

# Update repository
cd "${liar_repository}"
if git status --porcelain ${LIAR_SOFTWARE_FILE} | grep ${LIAR_SOFTWARE_FILE}; then
    git add ${LIAR_SOFTWARE_FILE}
    git commit -m"Automatic URL update"
    git push
fi
