#!/usr/bin/env bash

#
# liar update script for liar-software
#

LIAR_REPOSITORY_URL=git@framagit.org:grumpyf0x48/liar.git
LIAR_UPDATE_REPOSITORY_URL=git@framagit.org:grumpyf0x48/liar-update-software.git

if [ $# -lt 1 ]; then
    echo "Usage $0 DAILY | WEEKLY | MONTHLY" >&2
    exit 1
fi

LIAR_PERIODICITY="$1"
exec > "${LIAR_UPDATE_REPOSITORY}/$(basename "$0")-${LIAR_PERIODICITY}.log" 2>&1

# Make sure Maven and Java are in the crontab environment
export JAVA_HOME=/usr/lib/jvm/jdk8/jdk1.8.0_231
export GRAALVM_HOME=/usr/lib/jvm/graalvm/graalvm-ce-java8-20.1.0
PATH=~/bin:${JAVA_HOME}/bin:${PATH}

# Clone repositories
LIAR_REPOSITORY=$(mktemp -d)
git clone "${LIAR_REPOSITORY_URL}" "${LIAR_REPOSITORY}"

LIAR_UPDATE_REPOSITORY=$(mktemp -d)
git clone "${LIAR_UPDATE_REPOSITORY_URL}" "${LIAR_UPDATE_REPOSITORY}"

# Run update
make -C "${LIAR_UPDATE_REPOSITORY}" LIAR_REPOSITORY="${LIAR_REPOSITORY}" LIAR_PERIODICITY="${LIAR_PERIODICITY}" update_software_native

# Commit changes to repository
LIAR_SOFTWARE_FILE=liar-software
cd "${LIAR_REPOSITORY}"
if git status --porcelain ${LIAR_SOFTWARE_FILE} | grep ${LIAR_SOFTWARE_FILE}; then
    git add ${LIAR_SOFTWARE_FILE}
    git commit -m"${LIAR_PERIODICITY} Automatic URL update"
    git push
fi
