#!/bin/bash

#
# Copyright (C) 2017 Pierre-Yves Fourmond.

# This file is part of liar, the Linux Installer for ARchives.

# liar is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# liar is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with liar. If not, see <http://www.gnu.org/licenses/>.
#

#
# This file is used by liar-completion, which defines Bash tab auto-completion rules for the liar command.
#

LIAR=.liar_software
VERSION=0.2-dev

if [ "$1" = "version" ]; then
    echo "$LIAR version $VERSION"
fi

software_list=(
ant
atom
cheat
clion
evans
firefox
go
goland
graalvm
gradle
groovy
grpcui
grpcurl
hadolint
hugo
icecat
idea_community
idea_edu
idea_ultimate
jbang
jdk9
jdk10
jdk11
jdk12
jdk13
jdk14
jdk_ea15
jdk_ri7
jdk_ri8
jdk_ri9
jdk_ri10
jdk_ri11
jdk_ri12
jdk_ri13
jdk_ri14
jgo
jq
marp_cli
maven
micronaut
mongodb
node
postman
pycharm_community
pycharm_edu
pycharm_professional
robo3t
rubymine
sbt
scala
spring
sublimemerge
sublimetext
torbrowser
visualvm
webstorm
xsv
yq
)

ant=https://www-eu.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.zip
atom=https://github.com/atom/atom/releases/download/v1.35.1/atom-amd64.tar.gz
cheat=https://github.com/cheat/cheat/releases/download/4.0.1/cheat-linux-amd64.gz
clion=https://download.jetbrains.com/cpp/CLion-2020.1.0.tar.gz
easy_rsa=https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.6/EasyRSA-3.0.6.tgz
evans=https://github.com/ktr0731/evans/releases/download/0.8.4/evans_linux_amd64.tar.gz
firefox=https://download-installer.cdn.mozilla.net/pub/firefox/releases/66.0.2/linux-x86_64/fr/firefox-66.0.2.tar.bz2
go=https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz
goland=https://download.jetbrains.com/go/goland-2018.3.6.tar.gz
graalvm=https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-linux-amd64-19.2.1.tar.gz
gradle=https://downloads.gradle.org/distributions/gradle-5.3.1-bin.zip
groovy=https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.5.6.zip
grpcui=https://github.com/fullstorydev/grpcui/releases/download/v0.2.0/grpcui_0.2.0_linux_x86_64.tar.gz
grpcurl=https://github.com/fullstorydev/grpcurl/releases/download/v1.4.0/grpcurl_1.4.0_linux_x86_64.tar.gz
hadolint=https://github.com/hadolint/hadolint/releases/download/v1.17.6/hadolint-Linux-x86_64
hugo=https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.tar.gz
icecat=https://ftp.gnu.org/gnu/gnuzilla/60.3.0/icecat-60.3.0.en-US.gnulinux-x86_64.tar.bz2
idea_community=https://download.jetbrains.com/idea/ideaIC-2018.3.6.tar.gz
idea_edu=https://download.jetbrains.com/idea/ideaIE-2020.0.tar.gz
idea_ultimate=https://download.jetbrains.com/idea/ideaIU-2018.3.6.tar.gz
jbang=https://github.com/jbangdev/jbang/releases/download/v0.25.0/jbang-0.25.0.zip
jdk10=https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz
jdk11=https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
jdk12=https://download.java.net/java/GA/jdk12/GPL/openjdk-12_linux-x64_bin.tar.gz
jdk_ri7=https://download.java.net/openjdk/jdk7u75/ri/openjdk-7u75-b13-linux-x64-18_dec_2014.tar.gz
jdk_ri8=https://download.java.net/openjdk/jdk8u40/ri/openjdk-8u40-b25-linux-x64-10_feb_2015.tar.gz
jdk_ri9=https://download.java.net/openjdk/jdk9/ri/openjdk-9+181_linux-x64_ri.zip
jdk_ri10=https://download.java.net/openjdk/jdk10/ri/openjdk-10+44_linux-x64_bin_ri.tar.gz
jdk_ri11=https://download.java.net/openjdk/jdk11/ri/openjdk-11+28_linux-x64_bin.tar.gz
jgo=https://github.com/scijava/jgo/archive/0.3.0.zip
jq=https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
marp_cli=https://github.com/marp-team/marp-cli/releases/download/v0.14.1/marp-cli-v0.14.1-linux.tar.gz
maven=http://apache.mediamirrors.org/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz
micronaut=https://github.com/micronaut-projects/micronaut-starter/releases/download/v2.0.0/micronaut-cli-2.0.0.zip
mongodb=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-debian10-4.4.1.tgz
pycharm_community=https://download.jetbrains.com/python/pycharm-community-2019.1.1.tar.gz
pycharm_edu=https://download.jetbrains.com/python/pycharm-edu-2020.0.tar.gz
pycharm_professional=https://download.jetbrains.com/python/pycharm-professional-2019.1.1.tar.gz
robo3t=https://download.robomongo.org/1.2.1/linux/robo3t-1.2.1-linux-x86_64-3e50a65.tar.gz
rubymine=https://download.jetbrains.com/ruby/RubyMine-2018.3.5.tar.gz
scala=https://downloads.lightbend.com/scala/2.12.8/scala-2.12.8.tgz
spring=https://repo.spring.io/release/org/springframework/boot/spring-boot-cli/2.3.0.RELEASE/spring-boot-cli-2.3.0.RELEASE-bin.zip
sublimetext=https://download.sublimetext.com/sublime_text_3_build_3200_x64.tar.bz2
torbrowser=https://dist.torproject.org/torbrowser/10.0/tor-browser-linux64-10.0_fr.tar.xz
visualvm=https://github.com/visualvm/visualvm.src/releases/download/1.4.2/visualvm_142.zip
webstorm=https://download.jetbrains.com/webstorm/WebStorm-2018.3.6.tar.gz
xsv=https://github.com/BurntSushi/xsv/releases/download/0.13.0/xsv-0.13.0-x86_64-unknown-linux-musl.tar.gz
yq=https://github.com/mikefarah/yq/releases/download/3.3.1/yq_linux_amd64
